# Use an official Nginx image as the base image
FROM nginx:alpine

# Install git
RUN apk add --no-cache git

# Use an official PHP image as the base image
FROM php:7.4-apache

# Copy the HTML and PHP files to the Apache web server directory
COPY /app /var/www/html/

# Expose port 80 to be able to access the web server
EXPOSE 80
#https://github.com/tillerperry/WebContainer/tree/fadf77a4ad7c4ac190322613d00a3d27ca944f0a/Version1

# Expose port 80 to be able to access the web server
EXPOSE 80

# Start Nginx when the container launches
CMD ["nginx", "-g", "daemon off;"]