# Use an official PHP image as the base image
FROM php:7.4-apache

# Copy the HTML and PHP files to the Apache web server directory
COPY /app /var/www/html/

# Expose port 80 to be able to access the web server
EXPOSE 80